### ISSUE TITLE
Unsupported DecSync version

### ISSUE THREAD

**Issue by java-py-c-cpp-js** [39aldo39/Radicale-DecSync#19]
If I start the version installed via
```
pip3 install radicale_storage_decsync
```
I get the following error if I try syncing my calendars with Thunderbird:
```
ERROR: An exception occurred during PROPFIND request on '/user/calendars-colID#######/': DecSync: Unsupported DecSync version
```
Because AFAIK `pip3` should always install the most current version, I'm wondering why I get this error.

**Comment by java-py-c-cpp-js** [comment]
Found the error:
`pip3` DID install the most current version of `radicale_storage_decsync`, but there was an old, outdated version of `libdecsync` installing. 
Running `pip3 install -U libdecsync radicale_storage_decsync` fixes this issue.

**Comment by 39aldo39** [comment]
Glad you fixed it, but I am surprised it happened at all. The latest version of `radicale_storage_decsync` requires a libdecsync version of at least `2.0.0`, so it should have updated that one as well.
