### ISSUE TITLE
Add macOs support

### ISSUE THREAD

**Issue by Mugen36** [39aldo39/Radicale-DecSync#26]
Add macOs support

And thanks for your work, btw!

**Comment by onokatio** [comment]
I can run radicale on MacOS. Did you try it?

**Comment by Mugen36** [comment]
@onokatio 
yes, I did, but I could not install Dec-Sync for radicale on radical running on MacOS.

**Comment by onokatio** [comment]
> @onokatio yes, I did, but I could not install Dec-Sync for radicale on radical running on MacOS.

How is your radicale output going?
You have to install radicale-decsync to same site-packages location that you installed radicale (os package manager, pyenv, homebrew, or another independent environment).

**Comment by Mugen36** [comment]
Sorry for the late reply.
This was the error message:
` [CRITICAL] An exception occurred during server startup: Failed to load storage module ‘radicale_storage_decsync’: libdecsync: Operating system ‘Darwin’ not supported`

However, it seems to be working now, after I tried it again today with updated python3, decsync, radicale.
For reference, here someone described the same problem.
https://forum.syncthing.net/t/decsync-on-macos/15562/2
