### ISSUE TITLE
Windows 10 - Failed to load storage module

### ISSUE THREAD

**Issue by lukasubo** [39aldo39/Radicale-DecSync#4]
Following install instructions with latest python 3.8.4 leads to the following error.

`[2020-07-14 00:22:06 -0400] [6044] [CRITICAL] An exception occurred during server startup: Failed to load storage module 'radicale_storage_decsync': [WinError 193] %1 is not a valid Win32 application`

Thanks

**Comment by lukasubo** [comment]
Found the issue, Python3 64 bit must be installed. Pip will install Radicale-DecSync fine with 32 bit python, but it will not run.

**Comment by 39aldo39** [comment]
Indeed, the problem is that libdecsync requires a 64 bit python. I have added a check, so the error message will be clearer in the future. Thanks!
