### ISSUE TITLE
Crash when importing ics file through thunderbird lightening

### ISSUE THREAD

**Issue by renyuneyun** [39aldo39/Radicale-DecSync#7]
From #5, I figured out that I need to import the calendar (`.ics` file) through lightening (of thunderbird) rather than the radicale web interface.

However, when importing the file (which is exported from google calendar web interface), the radicale process crashes in the middle. Trying importing again causes it to crash immediately (i.e. without a few "importing..." in the beginning).

I'm not familiar with either DecSync or radicale codebase, so I'm not sure what debug information I should show.

Could this be due to non-Latin text? Some of my calendar entries contain Chinese characters.

**Comment by 39aldo39** [comment]
> I'm not familiar with either DecSync or radicale codebase, so I'm not sure what debug information I should show.

It would be very useful if you could run Radicale with the `--debug` option, and give some (censored) output around the crash. It is also good to know the versions of your packages. Most importantly, `radicale`, `radicale_storage_decsync` and `libdecsync`. You can get that info by executing `pip3 show X`.

> Could this be due to non-Latin text? Some of my calendar entries contain Chinese characters.

It shouldn't be as it should support Unicode, but you never know...

**Comment by renyuneyun** [comment]
Interesting... It now doesn't crash.
I'll keep using it an occasionally try the importing. I'll close this issue soon if I can't reproduce it :) , but may reopen it when it appears again :(

**Comment by renyuneyun** [comment]
I can't make it reappear... I'm closing this for the moment.
